// Generated by ng g component components/nav-bar 
import { Component } from '@angular/core';

@Component({
  selector: 'app-nav-bar',   // Use this in the HTML as the tab for the component
  imports: [],
  templateUrl: './nav-bar.html',
  styleUrl: './nav-bar.css'
})
export class NavBar {

}
